"""phase 6 social listening

Revision ID: 2b9f8779d140
Revises: c484073763d6
Create Date: 2026-09-08 08:18:25.372375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9f8779d140'
down_revision: Union[str, None] = 'c484073763d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('client_subjects',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('backfilled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('x_access', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('x_spend_ceiling_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'entity_id')
    )
    op.create_table('entity_social_configs',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('x_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('x_spend_usd', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('x_spend_period_start', sa.Date(), nullable=True),
    sa.Column('x_last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('youtube_last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('social_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('X', 'YOUTUBE', name='social_source'), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'source', 'url', name='uq_social_mention_entity_source_url')
    )
    op.create_index(op.f('ix_social_mentions_entity_id'), 'social_mentions', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_mentions_entity_id'), table_name='social_mentions')
    op.drop_table('social_mentions')
    op.drop_table('entity_social_configs')
    op.drop_table('client_subjects')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
    # social_source is only used by social_mentions, dropped above - clean
    # up the orphaned PG enum type too (see the phase 5 migration for why
    # this isn't automatic).
    sa.Enum(name='social_source').drop(op.get_bind(), checkfirst=True)
