"""add content-derived geography to system_tags and social_mentions

Revision ID: 339a3caf8f23
Revises: b7677f671992
Create Date: 2026-09-08 13:39:33.592438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339a3caf8f23'
down_revision: Union[str, None] = 'b7677f671992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Not autogenerated as-is: op.add_column with a brand-new sa.Enum
    # doesn't emit CREATE TYPE on Postgres - create it explicitly once,
    # then reference it with create_type=False from both columns that use
    # it (same DuplicateObject gotcha as f4bcd74b9b69, "new type" side).
    seat_type_enum = sa.Enum('MP', 'MLA', name='seat_type')
    seat_type_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust for enum reuse ###
    op.add_column('social_mentions', sa.Column('state', sa.String(length=128), nullable=True))
    op.add_column('social_mentions', sa.Column('district', sa.String(length=128), nullable=True))
    op.add_column('social_mentions', sa.Column('constituency', sa.String(length=255), nullable=True))
    op.add_column(
        'social_mentions',
        sa.Column('seat_type', sa.Enum('MP', 'MLA', name='seat_type', create_type=False), nullable=True),
    )
    op.add_column('system_tags', sa.Column('state', sa.String(length=128), nullable=True))
    op.add_column('system_tags', sa.Column('district', sa.String(length=128), nullable=True))
    op.add_column('system_tags', sa.Column('constituency', sa.String(length=255), nullable=True))
    op.add_column(
        'system_tags',
        sa.Column('seat_type', sa.Enum('MP', 'MLA', name='seat_type', create_type=False), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.drop_column('system_tags', 'seat_type')
    op.drop_column('system_tags', 'constituency')
    op.drop_column('system_tags', 'district')
    op.drop_column('system_tags', 'state')
    op.drop_column('social_mentions', 'seat_type')
    op.drop_column('social_mentions', 'constituency')
    op.drop_column('social_mentions', 'district')
    op.drop_column('social_mentions', 'state')
    # ### end Alembic commands ###
    # Autogenerate doesn't drop enum types on its own - seat_type is only
    # ever used by the two columns just dropped above, so it's safe to
    # clean up here too, same convention as c484073763d6's downgrade.
    sa.Enum(name='seat_type').drop(op.get_bind(), checkfirst=True)
