"""phase 3: admin auth fields, queue assignment, review indexes

Revision ID: 452f47392b85
Revises: 5c75be845006
Create Date: 2026-09-04 07:07:39.207144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '452f47392b85'
down_revision: Union[str, None] = '5c75be845006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # username/password_hash NOT NULL is safe unbackfilled: admins has been
    # empty since Phase 1 (no admin UI/login existed until this phase).
    op.add_column('admins', sa.Column('username', sa.String(length=64), nullable=False))
    op.add_column('admins', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('admins', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_unique_constraint(None, 'admins', ['username'])
    op.add_column('articles', sa.Column('assigned_admin_id', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_articles_assigned_admin_id'), 'articles', ['assigned_admin_id'], unique=False)
    op.create_foreign_key(None, 'articles', 'admins', ['assigned_admin_id'], ['id'])
    op.create_index(op.f('ix_reviews_admin_id'), 'reviews', ['admin_id'], unique=False)
    op.create_index(op.f('ix_reviews_decision'), 'reviews', ['decision'], unique=False)
    op.create_index(op.f('ix_reviews_timestamp'), 'reviews', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_timestamp'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_decision'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_admin_id'), table_name='reviews')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_index(op.f('ix_articles_assigned_admin_id'), table_name='articles')
    op.drop_column('articles', 'queued_at')
    op.drop_column('articles', 'assigned_admin_id')
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_column('admins', 'is_active')
    op.drop_column('admins', 'password_hash')
    op.drop_column('admins', 'username')
    # ### end Alembic commands ###
