"""phase 2: embeddings, entity trigger flag, system_tag provider

Revision ID: 5c75be845006
Revises: 4195c7a673a2
Create Date: 2026-08-28 05:09:56.470227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '5c75be845006'
down_revision: Union[str, None] = '4195c7a673a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True))
    op.add_column('articles', sa.Column('embedding_model', sa.String(length=128), nullable=True))
    op.add_column('articles', sa.Column('entity_trigger_override', sa.Boolean(), server_default='false', nullable=False))
    # NOT NULL is safe unbackfilled: system_tags has been empty since Phase 1
    # (nothing wrote to it until this phase's classifier).
    op.add_column('system_tags', sa.Column('provider', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_tags', 'provider')
    op.drop_column('articles', 'entity_trigger_override')
    op.drop_column('articles', 'embedding_model')
    op.drop_column('articles', 'embedding')
    # ### end Alembic commands ###
