"""phase 3: full-text scraping fields for admin review

Revision ID: 65d49d2d8e03
Revises: 452f47392b85
Create Date: 2026-09-04 07:59:27.980574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d49d2d8e03'
down_revision: Union[str, None] = '452f47392b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('scraped_body_text', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('scrape_attempted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('articles', sa.Column('scrape_error', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'scrape_error')
    op.drop_column('articles', 'scrape_attempted_at')
    op.drop_column('articles', 'scraped_body_text')
    # ### end Alembic commands ###
