"""add needs_manual_link_review to articles

Revision ID: 8e0a29dae4cf
Revises: 65d49d2d8e03
Create Date: 2026-09-04 11:44:46.213880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e0a29dae4cf'
down_revision: Union[str, None] = '65d49d2d8e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('needs_manual_link_review', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'needs_manual_link_review')
    # ### end Alembic commands ###
