"""add client subject youtube_access toggle

Revision ID: ab0cb9d2220f
Revises: bb1b1d8ab275
Create Date: 2026-09-08 12:25:07.845348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab0cb9d2220f'
down_revision: Union[str, None] = 'bb1b1d8ab275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_subjects', sa.Column('youtube_access', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_subjects', 'youtube_access')
    # ### end Alembic commands ###
