"""add engagement_count and per-entity social fetch config

Revision ID: b7677f671992
Revises: c1725431466e
Create Date: 2026-09-08 13:01:28.301571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7677f671992'
down_revision: Union[str, None] = 'c1725431466e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_social_configs', sa.Column('social_fetch_max_results', sa.Integer(), nullable=True))
    op.add_column('entity_social_configs', sa.Column('social_fetch_lookback_days', sa.Integer(), nullable=True))
    op.add_column('social_mentions', sa.Column('engagement_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_mentions', 'engagement_count')
    op.drop_column('entity_social_configs', 'social_fetch_lookback_days')
    op.drop_column('entity_social_configs', 'social_fetch_max_results')
    # ### end Alembic commands ###
