"""add news_access, default youtube_access off

Revision ID: c1725431466e
Revises: f4bcd74b9b69
Create Date: 2026-09-08 12:54:54.425335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1725431466e'
down_revision: Union[str, None] = 'f4bcd74b9b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_subjects', sa.Column('news_access', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###
    # Not autogenerated - alembic's autogenerate doesn't compare
    # server_default changes by default (compare_server_default isn't
    # enabled in env.py). Existing rows keep whatever youtube_access value
    # they already had - only the default for FUTURE rows changes, per
    # direct instruction ("on adding the client...") about creation-time
    # behavior, not a retroactive flip of already-tracked subjects.
    op.alter_column('client_subjects', 'youtube_access', server_default='false')


def downgrade() -> None:
    op.alter_column('client_subjects', 'youtube_access', server_default='true')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_subjects', 'news_access')
    # ### end Alembic commands ###
