"""phase 5 entity tagging and subject sentiment

Revision ID: c484073763d6
Revises: 8e0a29dae4cf
Create Date: 2026-09-08 07:42:13.201122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c484073763d6'
down_revision: Union[str, None] = '8e0a29dae4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic, hand-adjusted for enum reuse ###
    # subject_sentiment is a genuinely new type but is used by TWO columns
    # below - only the first column's Enum object should issue CREATE TYPE,
    # the second must pass create_type=False or Postgres errors with
    # "type already exists". review_decision already exists (created by
    # the reviews table's own earlier migration) - reusing it here for
    # subject_sentiment_decision must always be create_type=False.
    subject_sentiment_enum = postgresql.ENUM('FAVORABLE', 'UNFAVORABLE', 'NEUTRAL', name='subject_sentiment')
    subject_sentiment_enum_no_create = postgresql.ENUM(
        'FAVORABLE', 'UNFAVORABLE', 'NEUTRAL', name='subject_sentiment', create_type=False
    )
    review_decision_enum_no_create = postgresql.ENUM(
        'AGREED_WITH_SYSTEM', 'OVERRODE', name='review_decision', create_type=False
    )

    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('PERSON', 'PARTY', name='entity_type'), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String(length=255)), server_default='{}', nullable=False),
    sa.Column('entity_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('article_entities',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('in_headline', sa.Boolean(), nullable=False),
    sa.Column('first_mention_offset', sa.Integer(), nullable=False),
    sa.Column('prominence', sa.Enum('PRIMARY', 'SECONDARY', 'MENTIONED', name='entity_prominence'), nullable=False),
    sa.Column('system_subject_sentiment', subject_sentiment_enum, nullable=False),
    sa.Column('subject_sentiment_confidence', sa.Float(), nullable=False),
    sa.Column('subject_sentiment_provider', sa.String(length=64), nullable=False),
    sa.Column('published_subject_sentiment', subject_sentiment_enum_no_create, nullable=True),
    sa.Column('subject_sentiment_decision', review_decision_enum_no_create, nullable=True),
    sa.Column('subject_sentiment_reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('subject_sentiment_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['subject_sentiment_reviewed_by_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'entity_id')
    )
    op.add_column('articles', sa.Column('entities_extracted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'entities_extracted_at')
    op.drop_table('article_entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
    # Autogenerate doesn't drop enum types on its own (other tables could
    # in principle still reference them) - these three are only ever used
    # by the two tables just dropped above, so it's safe to clean them up
    # here too, rather than leaving orphaned PG types behind.
    sa.Enum(name='entity_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='entity_prominence').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='subject_sentiment').drop(op.get_bind(), checkfirst=True)
