"""add sentiment and confidence to social mentions

Revision ID: f4bcd74b9b69
Revises: ab0cb9d2220f
Create Date: 2026-09-08 12:34:34.541111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4bcd74b9b69'
down_revision: Union[str, None] = 'ab0cb9d2220f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # create_type=False: 'subject_sentiment' already exists (created by
    # ArticleEntity's Phase 5 migration) - see README's note on this same
    # DuplicateObject gotcha the first time a shared enum type was reused.
    op.add_column(
        'social_mentions',
        sa.Column('sentiment', sa.Enum('FAVORABLE', 'UNFAVORABLE', 'NEUTRAL', name='subject_sentiment', create_type=False), nullable=True),
    )
    op.add_column('social_mentions', sa.Column('sentiment_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_mentions', 'sentiment_confidence')
    op.drop_column('social_mentions', 'sentiment')
    # ### end Alembic commands ###
